# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master 
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/xenial64"
    master.vm.hostname = "master.example.com"
    master.vm.network "private_network", ip: "172.16.1.100"
    master.vm.provider "virtualbox" do |v|
      v.name = "master"
      v.memory = 2048
      v.cpus = 2
    end
    master.vm.provision "shell", path: "bootstrap_k8s.sh"
  end

  NodeCount = 1

  # Kubernetes Minions
  (1..NodeCount).each do |i|
    config.vm.define "minion#{i}" do |minion|
      minion.vm.box = "ubuntu/xenial64"
      minion.vm.hostname = "minion#{i}.example.com"
      minion.vm.network "private_network", ip: "172.16.1.10#{i}"
      minion.vm.provider "virtualbox" do |v|
        v.name = "minion#{i}"
        v.memory = 2048
        v.cpus = 2
      end
    end
  end

end
