---
apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
  namespace: development
spec:
  type: NodePort
  ports:
  - port: 5001
    targetPort: 80
    name: result-service
  selector:
    app: result
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: khozemanullwala/examplevotingapp_result
        ports:
        - containerPort: 80
          name: result