---
apiVersion: v1
kind: Service
metadata:
  labels:
    apps: worker
  name: worker
  namespace: development
spec:
  clusterIP: None
  selector:
    app: worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: khozemanullwala/examplevotingapp_worker
        name: worker